[workspace]
[package]
version = "0.1.0"
name = "pos-consensus-proof"
edition = "2021"

[dependencies]
base64 = "0.22.1"
sha2 = "0.10.8"
bytes = "1.7.1"
prost = "0.13.1"
reth-primitives = { git = "https://github.com/jtguibas/reth.git", branch = "john/rsp-8e9e6ac", default-features = false, features = [
    "alloy-compat",
    "std",
    "k256"
] }
alloy-primitives = "0.7.2"
alloy-rlp = "0.3.4"

[build-dependencies]
prost-build = "0.13.1"

[patch.crates-io]
alloy-eips = { git = "https://github.com/jtguibas/alloy.git", branch = "john/rsp-8e9e6ac" }